FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends make rsync curl gnupg && rm -rf /var/lib/apt/lists/*

WORKDIR /docs

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["make", "serve"]
